FROM debian:bullseye

# Update bullseye repositories
RUN sed -i -e 's/deb.debian.org/archive.debian.org/g' \
           -e 's|security.debian.org|archive.debian.org/|g' \
           -e '/bullseye-updates/d' /etc/apt/sources.list

# Add "deb-src" lines for developer packages
RUN sed -i -e '/^deb / s/$/ contrib non-free/' /etc/apt/sources.list
RUN sed -i -e '/^deb-src / s/$/ main contrib non-free/' /etc/apt/sources.list

RUN apt update && apt install -y \
        curl \
        git \
        build-essential \
        cmake \
        jq \
        libpaho-mqtt-dev

ADD sources/ /opt/
ADD config/ /etc/inverter/

RUN cd /opt/inverter-cli && \
    mkdir bin && cmake . && make && mv inverter_poller bin/

HEALTHCHECK \
    --interval=30s \
    --timeout=10s \
    --start-period=1m \
    --retries=3 \
  CMD /opt/healthcheck

WORKDIR /opt
ENTRYPOINT ["/bin/bash", "/opt/inverter-mqtt/entrypoint.sh"]
